name: flux_store
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  flutter_bloc:
  equatable:
  google_fonts:
  gap:
  json_annotation:
  hugeicons:
  intl:
  animated_bottom_navigation_bar:
  otp_text_field:

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0
  json_serializable:
  build_runner:





flutter:

  
  
  
  uses-material-design: true


  assets:
    - asset/image/png/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
