name: flux_store
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: any
  flutter_bloc: any
  equatable: any
  google_fonts: any
  gap: any
  json_annotation: any
  hugeicons: any
  intl: any
  dependencies: any
  pinput: any
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: any
  json_serializable: any
  build_runner: any





flutter:

  
  
  
  uses-material-design: true


  assets:
    - asset/image/png/
    - asset/image/svg/social_media_icons/
    - asset/image/svg/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
